### ISSUE TITLE
HardwareVideoEncoderFactory crashes for under API 19 devices

### ISSUE THREAD

**Issue by buttiiburak** [voximplant/android-sdk-demo#2] opened 2019-05-17 07:36 UTC
Hello,
There is a issue about API 19 and below devices. After calling Voximplant.getClientInstance(...),
got this crash for only API 19 and below devices. Any idea about this crash and any solution about it. The stacktrace is below.

Thanks in advance

org.webrtc.HardwareVideoEncoderFactory.isSupportedCodec (HardwareVideoEncoderFactory.java:171)
--
  | org.webrtc.HardwareVideoEncoderFactory.findCodecForType (HardwareVideoEncoderFactory.java:157)
  | org.webrtc.HardwareVideoEncoderFactory.getSupportedCodecs (HardwareVideoEncoderFactory.java:120)
  | org.webrtc.DefaultVideoEncoderFactory.getSupportedCodecs (DefaultVideoEncoderFactory.java:48)
  | com.voximplant.sdk.internal.call.PCFactoryWrapper.createPeerConnectionFactoryInternal (PCFactoryWrapper.java:153)
  | com.voximplant.sdk.internal.call.PCFactoryWrapper.createPeerConnectionFactory (PCFactoryWrapper.java:73)
  | com.voximplant.sdk.internal.Client.<init> (Client.java:107)

**Comment by YuliaGrigorieva** [comment] 2019-05-17 08:13
Hello!

Thank you for reaching out to us!

Could you please provide the following information:
1. Android device model you have reproduced the issue on
2. Exception that causes the crash (from logcat)

Best regards,
Yulia Grigorieva

**Comment by buttiiburak** [comment] 2019-05-17 08:35
Hi,
First of all we are testing your sdk in our production environment. I saw these crashes on our crash report tool (crashlytics). 

1. Most of the devices (almost %98) are Samsung Galaxy Win with Android version 4.1.2. But there are some other devices like Asus, Nokia with Android 4.4.4 and 4.3 (not respectively).

2. Exception is java.lang.IllegalArgumentException and here is the stacktrace from our crash report tool:

android.media.MediaCodecList.getCodecCapabilities (MediaCodecList.java)
  | android.media.MediaCodecInfo.getCapabilitiesForType (MediaCodecInfo.java:211)
  | org.webrtc.HardwareVideoEncoderFactory.isSupportedCodec (HardwareVideoEncoderFactory.java:171)
  | org.webrtc.HardwareVideoEncoderFactory.findCodecForType (HardwareVideoEncoderFactory.java:157)
  | org.webrtc.HardwareVideoEncoderFactory.getSupportedCodecs (HardwareVideoEncoderFactory.java:120)
  | org.webrtc.DefaultVideoEncoderFactory.getSupportedCodecs (DefaultVideoEncoderFactory.java:48)
  | com.voximplant.sdk.internal.call.PCFactoryWrapper.createPeerConnectionFactoryInternal (PCFactoryWrapper.java:153)
  | com.voximplant.sdk.internal.call.PCFactoryWrapper.createPeerConnectionFactory (PCFactoryWrapper.java:73)
  | com.voximplant.sdk.internal.Client.<init> (Client.java:107)
  | com.voximplant.sdk.Voximplant.getClientInstance (Voximplant.java:52)

This crash occur when we call : 
`ClientConfig clientConfig = new ClientConfig();
IClient client = Voximplant.getClientInstance(Executors.newSingleThreadExecutor(), getApplicationContext(), clientConfig);`

**Comment by YuliaGrigorieva** [comment] 2019-05-17 08:54
Hello!

Thank you for providing additional information. We are investigating the issue and return back to you soon.

Best regards,
Yulia Grigorieva

**Comment by YuliaGrigorieva** [comment] 2019-05-17 15:30
Hello @buttiiburak !

We have just released Voximplant Android SDK 2.11.2 that contains the changes to handle the issue.

Please update Voximplant Android SDK in your project.

Please let me know if the issue is still reproducible or not.

Best regards,
Yulia Grigorieva

**Comment by buttiiburak** [comment] 2019-05-20 07:24
Thank you @YuliaGrigorieva,
I will let you know about the issue.

**Comment by YuliaGrigorieva** [comment] 2019-06-04 14:31
Closing the issue for now.
Feel free to reopen if you get it reproduced

**Closed as completed by YuliaGrigorieva** 2019-06-04 14:31 UTC
